name: PyPI
on:
  push:
    tags:
      - '*'
jobs:
  build-n-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          python -mpip install build
          python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
